const hotels = [
  {
    hotelCode: "LUX001",
    name: "The Grand Palace",
    brand: "LuxStay Signature",
    slug: "the-grand-palace",
    description: "A landmark sea-facing address on Marine Drive with grand suites, destination dining, and polished service tailored for celebratory escapes and executive stays.",
    starRating: 5,
    propertyType: "Hotel",
    address: { addressLine1: "Marine Drive", city: "Mumbai", state: "Maharashtra", country: "India", pincode: "400020" },
    amenities: ["Swimming Pool", "Spa", "Gym", "WiFi", "Restaurant", "Bar", "Parking", "Concierge"],
    pricing: { basePricePerNight: 12000, currency: "INR" },
    averageRating: 4.8,
    totalReviews: 247,
    status: "active",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 24 hours before check-in" },
    contact: { email: "reservations@grandpalace.com", phone: "+91 22 1234 5678" },
    roomThemes: [
      { code: "CR", name: "Cityline Room", multiplier: 0.8, adults: 2, children: 1, bedType: "Queen", roomSize: 320, totalRooms: 14, availableRooms: 10, amenities: ["AC", "WiFi", "Smart TV", "Mini Bar", "Work Desk"] },
      { code: "SH", name: "Sea Horizon Suite", multiplier: 1.55, adults: 3, children: 2, bedType: "King", roomSize: 560, totalRooms: 8, availableRooms: 6, amenities: ["AC", "WiFi", "Smart TV", "Jacuzzi", "Living Area", "Butler Service"] },
      { code: "PS", name: "Palace Signature Residence", multiplier: 2.2, adults: 4, children: 2, bedType: "King", roomSize: 840, totalRooms: 4, availableRooms: 2, amenities: ["Private Dining", "Jacuzzi", "Butler Service", "Sea View", "Lounge Access"] },
    ],
  },
  {
    hotelCode: "LUX002",
    name: "Azure Ocean Resort",
    brand: "LuxStay Premium",
    slug: "azure-ocean-resort",
    description: "A beachfront Goa resort with breezy villas, sunset decks, and private cabanas crafted for romance, long weekends, and indulgent ocean stays.",
    starRating: 5,
    propertyType: "Resort",
    address: { addressLine1: "Calangute Beach Road", city: "Goa", state: "Goa", country: "India", pincode: "403516" },
    amenities: ["Private Beach", "Infinity Pool", "Spa", "WiFi", "Water Sports", "Restaurant", "Bar", "Yoga Classes"],
    pricing: { basePricePerNight: 9500, currency: "INR" },
    averageRating: 4.9,
    totalReviews: 312,
    status: "active",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=80",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=1200&q=80",
    ],
    policies: { checkInTime: "15:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 48 hours before check-in" },
    contact: { email: "stay@azureresort.com", phone: "+91 832 999 8888" },
    roomThemes: [
      { code: "BL", name: "Beach Loft", multiplier: 0.85, adults: 2, children: 1, bedType: "Queen", roomSize: 340, totalRooms: 12, availableRooms: 9, amenities: ["AC", "WiFi", "Rain Shower", "Deck Seating", "Mini Bar"] },
      { code: "OV", name: "Ocean View Villa", multiplier: 1.45, adults: 3, children: 2, bedType: "King", roomSize: 590, totalRooms: 7, availableRooms: 4, amenities: ["Private Deck", "Ocean View", "Smart TV", "Bathtub", "Coffee Station"] },
      { code: "PC", name: "Private Cabana Suite", multiplier: 2.05, adults: 4, children: 2, bedType: "King", roomSize: 760, totalRooms: 5, availableRooms: 3, amenities: ["Plunge Pool", "Butler Service", "Outdoor Tub", "Bar Setup", "Sunset Dining"] },
    ],
  },
  {
    hotelCode: "LUX003",
    name: "Royal Heritage Haveli",
    brand: "LuxStay Heritage",
    slug: "royal-heritage-haveli",
    description: "A restored Jaipur haveli that layers frescoed courtyards, royal dining, and intimate heritage suites into an authentic old-city stay.",
    starRating: 4,
    propertyType: "Hotel",
    address: { addressLine1: "Old City, Near Amber Fort", city: "Jaipur", state: "Rajasthan", country: "India", pincode: "302001" },
    amenities: ["Heritage Tours", "Rooftop Restaurant", "WiFi", "Pool", "Cultural Events", "Spa", "Parking"],
    pricing: { basePricePerNight: 6500, currency: "INR" },
    averageRating: 4.7,
    totalReviews: 189,
    status: "active",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80",
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&q=80",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80",
    ],
    policies: { checkInTime: "13:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 24 hours before check-in" },
    contact: { email: "book@royalhaveli.com", phone: "+91 141 555 6789" },
    roomThemes: [
      { code: "CT", name: "Courtyard Chamber", multiplier: 0.78, adults: 2, children: 1, bedType: "Queen", roomSize: 290, totalRooms: 10, availableRooms: 7, amenities: ["AC", "WiFi", "Tea Station", "Courtyard View", "Writing Desk"] },
      { code: "MP", name: "Maharaja Pavilion", multiplier: 1.4, adults: 3, children: 1, bedType: "King", roomSize: 510, totalRooms: 6, availableRooms: 4, amenities: ["Daybed", "Bathtub", "Hand-painted Decor", "Lounge Seating", "Turndown Service"] },
      { code: "ZR", name: "Zenana Royal Suite", multiplier: 1.9, adults: 4, children: 2, bedType: "King", roomSize: 710, totalRooms: 3, availableRooms: 1, amenities: ["Private Dining", "Heritage Balcony", "Jacuzzi", "Butler Service", "Library Nook"] },
    ],
  },
  {
    hotelCode: "LUX004",
    name: "Himalayan Retreat",
    brand: "LuxStay Mountain",
    slug: "himalayan-retreat",
    description: "A cedar-and-stone mountain retreat with Himalayan panoramas, crackling fireplaces, and slow-travel comfort in the hills of Shimla.",
    starRating: 4,
    propertyType: "Resort",
    address: { addressLine1: "Mall Road", city: "Shimla", state: "Himachal Pradesh", country: "India", pincode: "171001" },
    amenities: ["Mountain Views", "Fireplace", "Trekking", "WiFi", "Restaurant", "Bonfire Area", "Library"],
    pricing: { basePricePerNight: 4800, currency: "INR" },
    averageRating: 4.6,
    totalReviews: 143,
    status: "active",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1519449556851-5720b33024e7?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1519449556851-5720b33024e7?w=1200&q=80",
      "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=1200&q=80",
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 72 hours before check-in" },
    contact: { email: "info@himalayanretreat.com", phone: "+91 177 222 3456" },
    roomThemes: [
      { code: "FF", name: "Forest Facing Room", multiplier: 0.74, adults: 2, children: 1, bedType: "Queen", roomSize: 300, totalRooms: 16, availableRooms: 11, amenities: ["Heater", "WiFi", "Tea Station", "Timber Interiors", "Window Bench"] },
      { code: "RV", name: "Ridge View Loft", multiplier: 1.3, adults: 3, children: 2, bedType: "King", roomSize: 480, totalRooms: 7, availableRooms: 5, amenities: ["Balcony", "Fireplace", "Smart TV", "Walk-in Shower", "Mountain View"] },
      { code: "AS", name: "Alpine Family Suite", multiplier: 1.8, adults: 4, children: 2, bedType: "King", roomSize: 690, totalRooms: 4, availableRooms: 2, amenities: ["Living Area", "Fireplace", "Pantry", "Family Lounge", "View Deck"] },
    ],
  },
  {
    hotelCode: "LUX005",
    name: "Beachfront Serenity Villa",
    brand: "LuxStay Villas",
    slug: "beachfront-serenity-villa",
    description: "A private villa-style coastal stay in Kerala with spice-garden pathways, Ayurvedic rituals, and premium backwater-side privacy.",
    starRating: 5,
    propertyType: "Villa",
    address: { addressLine1: "Kumarakom Lake Road", city: "Kochi", state: "Kerala", country: "India", pincode: "686566" },
    amenities: ["Private Pool", "Backwater Views", "Ayurveda Spa", "WiFi", "Butler Service", "Boat Rides", "Organic Garden"],
    pricing: { basePricePerNight: 15000, currency: "INR" },
    averageRating: 4.9,
    totalReviews: 98,
    status: "active",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1200&q=80",
      "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=1200&q=80",
      "https://images.unsplash.com/photo-1465056836041-7f43ac27dcb5?w=1200&q=80",
    ],
    policies: { checkInTime: "15:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 48 hours before check-in" },
    contact: { email: "villa@serenity.com", phone: "+91 484 444 5678" },
    roomThemes: [
      { code: "GP", name: "Garden Pavilion", multiplier: 0.88, adults: 2, children: 1, bedType: "Queen", roomSize: 360, totalRooms: 8, availableRooms: 6, amenities: ["Garden View", "Rain Shower", "Mini Bar", "WiFi", "Verandah"] },
      { code: "BV", name: "Backwater Villa", multiplier: 1.5, adults: 3, children: 2, bedType: "King", roomSize: 620, totalRooms: 6, availableRooms: 4, amenities: ["Private Plunge Pool", "Deck Dining", "Bathtub", "Butler Service", "Canal View"] },
      { code: "LS", name: "Lotus Signature Residence", multiplier: 2.3, adults: 4, children: 2, bedType: "King", roomSize: 920, totalRooms: 3, availableRooms: 2, amenities: ["Private Pool", "Outdoor Lounge", "Spa Room", "Personal Chef", "Sunrise Deck"] },
    ],
  },
  {
    hotelCode: "LUX006",
    name: "The Urban Luxe",
    brand: "LuxStay City",
    slug: "the-urban-luxe",
    description: "A polished business hotel in Bengaluru with skyline bars, design-led rooms, and frictionless service for modern city stays.",
    starRating: 4,
    propertyType: "Hotel",
    address: { addressLine1: "Residency Road, MG Road", city: "Bangalore", state: "Karnataka", country: "India", pincode: "560025" },
    amenities: ["Rooftop Pool", "Sky Bar", "Business Center", "WiFi", "Gym", "Restaurant", "Parking", "EV Charging"],
    pricing: { basePricePerNight: 7500, currency: "INR" },
    averageRating: 4.5,
    totalReviews: 267,
    status: "active",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=1200&q=80",
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=1200&q=80",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 24 hours before check-in" },
    contact: { email: "stay@theurbanluxe.com", phone: "+91 80 9876 5432" },
    roomThemes: [
      { code: "SM", name: "Studio Metro Room", multiplier: 0.82, adults: 2, children: 1, bedType: "Queen", roomSize: 310, totalRooms: 18, availableRooms: 13, amenities: ["WiFi", "Smart TV", "Desk", "Espresso Kit", "Rain Shower"] },
      { code: "SB", name: "Skyline Business Suite", multiplier: 1.35, adults: 3, children: 1, bedType: "King", roomSize: 470, totalRooms: 9, availableRooms: 5, amenities: ["Executive Desk", "Lounge Access", "Bathtub", "Soundproofing", "City View"] },
      { code: "PR", name: "Penthouse Retreat", multiplier: 2.0, adults: 4, children: 2, bedType: "King", roomSize: 760, totalRooms: 4, availableRooms: 1, amenities: ["Private Bar", "Dining Area", "Jacuzzi", "Butler Service", "Panoramic Terrace"] },
    ],
  },
  {
    hotelCode: "LUX007",
    name: "Golden Sands Resort",
    brand: "LuxStay Premium",
    slug: "golden-sands-resort",
    description: "A desert-edge resort in Jaisalmer pairing dune safaris, folk evenings, and elegant tented-luxury inspired suites.",
    starRating: 4,
    propertyType: "Resort",
    address: { addressLine1: "Sam Sand Dunes Road", city: "Jaisalmer", state: "Rajasthan", country: "India", pincode: "345001" },
    amenities: ["Desert Safari", "Cultural Shows", "Rooftop Dining", "WiFi", "Pool", "Camel Rides", "Star Gazing"],
    pricing: { basePricePerNight: 8500, currency: "INR" },
    averageRating: 4.7,
    totalReviews: 156,
    status: "active",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&q=80",
      "https://images.unsplash.com/photo-1529551739587-e242c564f727?w=1200&q=80",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 48 hours before check-in" },
    contact: { email: "desert@goldensands.com", phone: "+91 2992 555 444" },
    roomThemes: [
      { code: "DS", name: "Dune Studio", multiplier: 0.8, adults: 2, children: 1, bedType: "Queen", roomSize: 330, totalRooms: 14, availableRooms: 10, amenities: ["WiFi", "Terrace Seating", "Tea Station", "Desert View", "AC"] },
      { code: "OC", name: "Oasis Courtyard Suite", multiplier: 1.42, adults: 3, children: 2, bedType: "King", roomSize: 520, totalRooms: 7, availableRooms: 4, amenities: ["Courtyard Lounge", "Bathtub", "Mini Bar", "Fire Pit Access", "Smart TV"] },
      { code: "SC", name: "Sandscape Camp Residence", multiplier: 1.95, adults: 4, children: 2, bedType: "King", roomSize: 720, totalRooms: 4, availableRooms: 2, amenities: ["Private Deck", "Star Gazing Bed", "Butler Service", "Outdoor Shower", "Dining Tent"] },
    ],
  },
  {
    hotelCode: "LUX008",
    name: "Nirvana Wellness Retreat",
    brand: "LuxStay Wellness",
    slug: "nirvana-wellness-retreat",
    description: "A wellness-first retreat in Rishikesh with restorative design, mindful dining, and holistic programming across every stay.",
    starRating: 4,
    propertyType: "Resort",
    address: { addressLine1: "Rajpur Road", city: "Rishikesh", state: "Uttarakhand", country: "India", pincode: "249137" },
    amenities: ["Yoga Studio", "Ayurveda Center", "Organic Restaurant", "WiFi", "Meditation Hall", "Riverside Walks", "Detox Programs"],
    pricing: { basePricePerNight: 5500, currency: "INR" },
    averageRating: 4.8,
    totalReviews: 203,
    status: "active",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80",
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1200&q=80",
    ],
    policies: { checkInTime: "15:00", checkOutTime: "10:00", cancellationPolicy: "Free cancellation until 72 hours before check-in" },
    contact: { email: "namaste@nirvana.com", phone: "+91 135 888 9999" },
    roomThemes: [
      { code: "CM", name: "Calm Minimal Room", multiplier: 0.78, adults: 2, children: 0, bedType: "Queen", roomSize: 290, totalRooms: 12, availableRooms: 8, amenities: ["Air Purifier", "Yoga Mats", "Herbal Tea", "WiFi", "Desk"] },
      { code: "RV", name: "Riverstone Suite", multiplier: 1.32, adults: 3, children: 1, bedType: "King", roomSize: 460, totalRooms: 8, availableRooms: 5, amenities: ["Meditation Deck", "Bathtub", "Healthy Minibar", "Sound System", "Balcony"] },
      { code: "AY", name: "Ayur Sanctuary Residence", multiplier: 1.85, adults: 4, children: 1, bedType: "King", roomSize: 700, totalRooms: 4, availableRooms: 2, amenities: ["Treatment Room", "Private Deck", "Living Lounge", "Steam Shower", "Pantry"] },
    ],
  },
  {
    hotelCode: "LUX009",
    name: "Emerald Lake Palace",
    brand: "LuxStay Heritage",
    slug: "emerald-lake-palace",
    description: "A romantic Udaipur hideaway overlooking shimmering waters with marble corridors, candlelit terraces, and regal suites.",
    starRating: 5,
    propertyType: "Hotel",
    address: { addressLine1: "Pichola Lake Road", city: "Udaipur", state: "Rajasthan", country: "India", pincode: "313001" },
    amenities: ["Lake View", "Spa", "WiFi", "Restaurant", "Bar", "Boat Transfers", "Concierge"],
    pricing: { basePricePerNight: 13800, currency: "INR" },
    averageRating: 4.9,
    totalReviews: 168,
    status: "active",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 48 hours before check-in" },
    contact: { email: "stay@emeraldlakepalace.com", phone: "+91 294 332 7788" },
    roomThemes: [
      { code: "LC", name: "Lake Court Room", multiplier: 0.84, adults: 2, children: 1, bedType: "Queen", roomSize: 340, totalRooms: 10, availableRooms: 7, amenities: ["WiFi", "Lake View", "Tea Service", "Desk", "Marble Bath"] },
      { code: "MR", name: "Mewar Royal Suite", multiplier: 1.52, adults: 3, children: 2, bedType: "King", roomSize: 600, totalRooms: 5, availableRooms: 3, amenities: ["Terrace Seating", "Butler Service", "Lounge", "Bathtub", "Dining Nook"] },
      { code: "CC", name: "Crystal Courtyard Residence", multiplier: 2.2, adults: 4, children: 2, bedType: "King", roomSize: 880, totalRooms: 3, availableRooms: 1, amenities: ["Private Terrace", "Jacuzzi", "Piano Lounge", "Chef on Call", "Sunset View"] },
    ],
  },
  {
    hotelCode: "LUX010",
    name: "Cedar Peak Lodge",
    brand: "LuxStay Mountain",
    slug: "cedar-peak-lodge",
    description: "A mountain lodge in Manali balancing alpine warmth, adventure access, and boutique hospitality for year-round escapes.",
    starRating: 4,
    propertyType: "Resort",
    address: { addressLine1: "Old Manali Road", city: "Manali", state: "Himachal Pradesh", country: "India", pincode: "175131" },
    amenities: ["Mountain Views", "Ski Concierge", "WiFi", "Bonfire", "Restaurant", "Spa", "Parking"],
    pricing: { basePricePerNight: 6200, currency: "INR" },
    averageRating: 4.6,
    totalReviews: 142,
    status: "active",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
      "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 72 hours before check-in" },
    contact: { email: "hello@cedarpeaklodge.com", phone: "+91 1902 448 228" },
    roomThemes: [
      { code: "WT", name: "Woodland Twin", multiplier: 0.76, adults: 2, children: 1, bedType: "Twin", roomSize: 305, totalRooms: 15, availableRooms: 9, amenities: ["Heater", "Balcony", "WiFi", "Tea Station", "Desk"] },
      { code: "AR", name: "Alpine Ridge Suite", multiplier: 1.33, adults: 3, children: 2, bedType: "King", roomSize: 500, totalRooms: 7, availableRooms: 5, amenities: ["Fireplace", "Mountain View", "Sofa Lounge", "Bathtub", "Coffee Machine"] },
      { code: "SC", name: "Summit Chalet Residence", multiplier: 1.92, adults: 4, children: 2, bedType: "King", roomSize: 760, totalRooms: 3, availableRooms: 1, amenities: ["Private Deck", "Jacuzzi", "Dining Corner", "Pantry", "Bonfire Setup"] },
    ],
  },
  {
    hotelCode: "LUX011",
    name: "Coral Reef Escape",
    brand: "LuxStay Island",
    slug: "coral-reef-escape",
    description: "A tropical island-style stay in the Andamans with marine adventures, reefside views, and breezy premium suites.",
    starRating: 5,
    propertyType: "Resort",
    address: { addressLine1: "Havelock Beach Front", city: "Port Blair", state: "Andaman and Nicobar Islands", country: "India", pincode: "744211" },
    amenities: ["Private Beach", "Diving Center", "WiFi", "Restaurant", "Spa", "Bar", "Airport Transfers"],
    pricing: { basePricePerNight: 14200, currency: "INR" },
    averageRating: 4.8,
    totalReviews: 154,
    status: "active",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&q=80",
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
    ],
    policies: { checkInTime: "15:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 5 days before check-in" },
    contact: { email: "book@coralreefescape.com", phone: "+91 3192 773 200" },
    roomThemes: [
      { code: "RS", name: "Reef Studio", multiplier: 0.83, adults: 2, children: 1, bedType: "Queen", roomSize: 330, totalRooms: 11, availableRooms: 8, amenities: ["WiFi", "Outdoor Shower", "Mini Bar", "Deck Chairs", "Smart TV"] },
      { code: "LB", name: "Lagoon Bungalow", multiplier: 1.48, adults: 3, children: 2, bedType: "King", roomSize: 610, totalRooms: 6, availableRooms: 4, amenities: ["Private Deck", "Ocean View", "Bathtub", "Coffee Bar", "Daybed"] },
      { code: "CT", name: "Coral Tide Residence", multiplier: 2.18, adults: 4, children: 2, bedType: "King", roomSize: 860, totalRooms: 3, availableRooms: 2, amenities: ["Plunge Pool", "Private Dining", "Butler Service", "Spa Bed", "Beach Cabana"] },
    ],
  },
  {
    hotelCode: "LUX012",
    name: "Ivory Business Hotel",
    brand: "LuxStay City",
    slug: "ivory-business-hotel",
    description: "A refined city stay in Hyderabad built around corporate convenience, fast service, and polished modern interiors.",
    starRating: 4,
    propertyType: "Hotel",
    address: { addressLine1: "Hitech City Main Road", city: "Hyderabad", state: "Telangana", country: "India", pincode: "500081" },
    amenities: ["Business Lounge", "WiFi", "Gym", "Restaurant", "Parking", "Airport Transfers", "Meeting Rooms"],
    pricing: { basePricePerNight: 7100, currency: "INR" },
    averageRating: 4.4,
    totalReviews: 201,
    status: "active",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80",
      "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?w=1200&q=80",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=80",
    ],
    policies: { checkInTime: "13:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 24 hours before check-in" },
    contact: { email: "sales@ivorybusinesshotel.com", phone: "+91 40 7007 1001" },
    roomThemes: [
      { code: "ER", name: "Executive Room", multiplier: 0.84, adults: 2, children: 1, bedType: "Queen", roomSize: 315, totalRooms: 20, availableRooms: 15, amenities: ["WiFi", "Desk", "Ergonomic Chair", "Tea Kit", "Smart TV"] },
      { code: "CS", name: "Club Signature Suite", multiplier: 1.36, adults: 3, children: 1, bedType: "King", roomSize: 490, totalRooms: 8, availableRooms: 4, amenities: ["Lounge Access", "Bathtub", "Espresso Machine", "Meeting Table", "City View"] },
      { code: "BR", name: "Boardroom Residence", multiplier: 1.88, adults: 4, children: 1, bedType: "King", roomSize: 720, totalRooms: 3, availableRooms: 1, amenities: ["Private Office", "Dining Space", "Pantry", "Host Desk", "Airport Transfer"] },
    ],
  },
  {
    hotelCode: "LUX013",
    name: "Saffron Courtyard Boutique",
    brand: "LuxStay Heritage",
    slug: "saffron-courtyard-boutique",
    description: "A boutique heritage retreat in Amritsar with intimate courtyards, Punjabi hospitality, and art-led interiors.",
    starRating: 4,
    propertyType: "Boutique",
    address: { addressLine1: "Hall Bazaar Road", city: "Amritsar", state: "Punjab", country: "India", pincode: "143001" },
    amenities: ["WiFi", "Restaurant", "Cultural Evenings", "Parking", "Tea Lounge", "Concierge", "Spa"],
    pricing: { basePricePerNight: 5900, currency: "INR" },
    averageRating: 4.5,
    totalReviews: 121,
    status: "active",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 36 hours before check-in" },
    contact: { email: "hello@saffroncourtyard.com", phone: "+91 183 221 4455" },
    roomThemes: [
      { code: "CV", name: "Courtyard Verandah Room", multiplier: 0.8, adults: 2, children: 1, bedType: "Queen", roomSize: 285, totalRooms: 9, availableRooms: 6, amenities: ["Verandah", "WiFi", "Tea Set", "Smart TV", "Handcrafted Decor"] },
      { code: "AC", name: "Artist Corner Suite", multiplier: 1.28, adults: 3, children: 1, bedType: "King", roomSize: 430, totalRooms: 5, availableRooms: 3, amenities: ["Bathtub", "Sitting Room", "Library Shelf", "Breakfast Service", "Courtyard View"] },
      { code: "PS", name: "Punjab Signature Loft", multiplier: 1.82, adults: 4, children: 2, bedType: "King", roomSize: 640, totalRooms: 2, availableRooms: 1, amenities: ["Dining Alcove", "Private Terrace", "Steam Shower", "Butler Service", "Lounge"] },
    ],
  },
  {
    hotelCode: "LUX014",
    name: "Rainforest Canopy Retreat",
    brand: "LuxStay Nature",
    slug: "rainforest-canopy-retreat",
    description: "An immersive eco-luxury escape in Coorg with rainforest views, spice trails, and beautifully quiet suites.",
    starRating: 5,
    propertyType: "Resort",
    address: { addressLine1: "Madikeri Plantation Road", city: "Coorg", state: "Karnataka", country: "India", pincode: "571201" },
    amenities: ["Nature Trails", "Infinity Pool", "WiFi", "Restaurant", "Spa", "Birdwatching", "Bonfire"],
    pricing: { basePricePerNight: 10400, currency: "INR" },
    averageRating: 4.8,
    totalReviews: 176,
    status: "active",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1444201983204-c43cbd584d93?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1444201983204-c43cbd584d93?w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
      "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?w=1200&q=80",
    ],
    policies: { checkInTime: "15:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 72 hours before check-in" },
    contact: { email: "stay@rainforestcanopy.com", phone: "+91 8272 117 880" },
    roomThemes: [
      { code: "CL", name: "Canopy Lodge Room", multiplier: 0.82, adults: 2, children: 1, bedType: "Queen", roomSize: 325, totalRooms: 12, availableRooms: 9, amenities: ["Forest View", "Rain Shower", "WiFi", "Coffee Press", "Deck"] },
      { code: "PW", name: "Plantation Walk Suite", multiplier: 1.38, adults: 3, children: 2, bedType: "King", roomSize: 520, totalRooms: 6, availableRooms: 4, amenities: ["Bathtub", "Lounge Corner", "Private Deck", "Tea Bar", "Valley View"] },
      { code: "TC", name: "Treehouse Collection Residence", multiplier: 2.04, adults: 4, children: 2, bedType: "King", roomSize: 770, totalRooms: 3, availableRooms: 1, amenities: ["Private Pool", "Outdoor Shower", "Hammock Deck", "Butler Service", "Sunrise View"] },
    ],
  },
  {
    hotelCode: "LUX015",
    name: "Harborline Suites",
    brand: "LuxStay Coastal",
    slug: "harborline-suites",
    description: "A refined harbor-facing stay in Chennai blending business access, sea breezes, and sophisticated contemporary rooms.",
    starRating: 4,
    propertyType: "Hotel",
    address: { addressLine1: "Marina Seafront", city: "Chennai", state: "Tamil Nadu", country: "India", pincode: "600005" },
    amenities: ["Sea View", "WiFi", "Gym", "Restaurant", "Business Lounge", "Parking", "Airport Transfers"],
    pricing: { basePricePerNight: 7800, currency: "INR" },
    averageRating: 4.5,
    totalReviews: 132,
    status: "active",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=80",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 24 hours before check-in" },
    contact: { email: "reservations@harborlinesuites.com", phone: "+91 44 6112 9900" },
    roomThemes: [
      { code: "BV", name: "Bay View Room", multiplier: 0.83, adults: 2, children: 1, bedType: "Queen", roomSize: 320, totalRooms: 16, availableRooms: 11, amenities: ["Sea View", "Desk", "WiFi", "Rain Shower", "Tea Station"] },
      { code: "HS", name: "Harbor Signature Suite", multiplier: 1.34, adults: 3, children: 1, bedType: "King", roomSize: 500, totalRooms: 7, availableRooms: 5, amenities: ["Bathtub", "Lounge Access", "Coffee Machine", "Dining Nook", "Skyline View"] },
      { code: "ML", name: "Marina Loft Residence", multiplier: 1.96, adults: 4, children: 2, bedType: "King", roomSize: 750, totalRooms: 3, availableRooms: 1, amenities: ["Private Bar", "Panoramic Deck", "Dining Area", "Butler Service", "Media Room"] },
    ],
  },
  {
    hotelCode: "LUX016",
    name: "Lotus Temple Residency",
    brand: "LuxStay Signature",
    slug: "lotus-temple-residency",
    description: "A quiet, design-led New Delhi retreat with serene interiors, efficient service, and polished premium suites near the city core.",
    starRating: 5,
    propertyType: "Hotel",
    address: { addressLine1: "Greater Kailash", city: "New Delhi", state: "Delhi", country: "India", pincode: "110048" },
    amenities: ["Spa", "WiFi", "Restaurant", "Bar", "Gym", "Parking", "Concierge"],
    pricing: { basePricePerNight: 11600, currency: "INR" },
    averageRating: 4.7,
    totalReviews: 194,
    status: "active",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1468824357306-a439d58ccb1c?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1468824357306-a439d58ccb1c?w=1200&q=80",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "12:00", cancellationPolicy: "Free cancellation until 36 hours before check-in" },
    contact: { email: "stay@lotustempleresidency.com", phone: "+91 11 4455 8800" },
    roomThemes: [
      { code: "LH", name: "Lotus Harmony Room", multiplier: 0.84, adults: 2, children: 1, bedType: "Queen", roomSize: 335, totalRooms: 18, availableRooms: 12, amenities: ["WiFi", "Tea Service", "Desk", "Rain Shower", "Smart TV"] },
      { code: "ES", name: "Embassy Suite", multiplier: 1.42, adults: 3, children: 2, bedType: "King", roomSize: 540, totalRooms: 8, availableRooms: 4, amenities: ["Lounge Access", "Bathtub", "Espresso Bar", "City View", "Soundproofing"] },
      { code: "PR", name: "Presidential Residence", multiplier: 2.15, adults: 4, children: 2, bedType: "King", roomSize: 820, totalRooms: 2, availableRooms: 1, amenities: ["Dining Room", "Private Study", "Butler Service", "Jacuzzi", "Terrace"] },
    ],
  },
  {
    hotelCode: "LUX017",
    name: "Sunset Cliff Resort",
    brand: "LuxStay Coastal",
    slug: "sunset-cliff-resort",
    description: "A dramatic clifftop stay in Varkala with golden-hour views, barefoot luxury, and easygoing premium hospitality.",
    starRating: 5,
    propertyType: "Resort",
    address: { addressLine1: "North Cliff Road", city: "Varkala", state: "Kerala", country: "India", pincode: "695141" },
    amenities: ["Cliff View", "Infinity Pool", "WiFi", "Spa", "Restaurant", "Yoga Deck", "Airport Transfers"],
    pricing: { basePricePerNight: 9800, currency: "INR" },
    averageRating: 4.8,
    totalReviews: 165,
    status: "active",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&q=80",
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1200&q=80",
      "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?w=1200&q=80",
    ],
    policies: { checkInTime: "15:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 48 hours before check-in" },
    contact: { email: "hello@sunsetcliffresort.com", phone: "+91 470 220 6677" },
    roomThemes: [
      { code: "CV", name: "Cliff View Room", multiplier: 0.82, adults: 2, children: 1, bedType: "Queen", roomSize: 320, totalRooms: 13, availableRooms: 9, amenities: ["Cliff View", "Rain Shower", "Deck Seating", "WiFi", "Mini Bar"] },
      { code: "SB", name: "Sunset Balcony Suite", multiplier: 1.4, adults: 3, children: 2, bedType: "King", roomSize: 510, totalRooms: 7, availableRooms: 4, amenities: ["Balcony", "Bathtub", "Espresso Kit", "Lounge", "Ocean View"] },
      { code: "PS", name: "Panorama Sky Residence", multiplier: 2.0, adults: 4, children: 2, bedType: "King", roomSize: 780, totalRooms: 3, availableRooms: 2, amenities: ["Private Pool", "Dining Deck", "Butler Service", "Outdoor Tub", "Sunset Lounge"] },
    ],
  },
  {
    hotelCode: "LUX018",
    name: "Vintage Vineyard Stay",
    brand: "LuxStay Countryside",
    slug: "vintage-vineyard-stay",
    description: "A countryside retreat in Nashik with vineyard trails, private tastings, and warm contemporary suites amid the vines.",
    starRating: 4,
    propertyType: "Boutique",
    address: { addressLine1: "Gangapur Vineyard Belt", city: "Nashik", state: "Maharashtra", country: "India", pincode: "422222" },
    amenities: ["Vineyard Tours", "WiFi", "Restaurant", "Pool", "Wine Tastings", "Parking", "Spa"],
    pricing: { basePricePerNight: 6900, currency: "INR" },
    averageRating: 4.6,
    totalReviews: 110,
    status: "active",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1468824357306-a439d58ccb1c?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1468824357306-a439d58ccb1c?w=1200&q=80",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=1200&q=80",
      "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 48 hours before check-in" },
    contact: { email: "book@vintagevineyardstay.com", phone: "+91 253 881 2200" },
    roomThemes: [
      { code: "VG", name: "Vine Garden Room", multiplier: 0.8, adults: 2, children: 1, bedType: "Queen", roomSize: 300, totalRooms: 10, availableRooms: 7, amenities: ["Patio", "WiFi", "Tea Kit", "Smart TV", "Garden View"] },
      { code: "BT", name: "Barrel Tasting Suite", multiplier: 1.33, adults: 3, children: 1, bedType: "King", roomSize: 470, totalRooms: 5, availableRooms: 3, amenities: ["Bathtub", "Wine Fridge", "Lounge Seating", "Deck", "Breakfast Setup"] },
      { code: "SE", name: "Sommelier Estate Residence", multiplier: 1.9, adults: 4, children: 2, bedType: "King", roomSize: 720, totalRooms: 2, availableRooms: 1, amenities: ["Private Cellar", "Dining Room", "Outdoor Tub", "Pantry", "Vineyard View"] },
    ],
  },
  {
    hotelCode: "LUX019",
    name: "Aurora Snowview Resort",
    brand: "LuxStay Mountain",
    slug: "aurora-snowview-resort",
    description: "A Gulmarg resort designed for snow-season magic, ski access, and cocooning comfort with warm premium interiors.",
    starRating: 5,
    propertyType: "Resort",
    address: { addressLine1: "Gulmarg Gondola Road", city: "Gulmarg", state: "Jammu and Kashmir", country: "India", pincode: "193403" },
    amenities: ["Ski Concierge", "Mountain Views", "WiFi", "Spa", "Restaurant", "Fireplace Lounge", "Parking"],
    pricing: { basePricePerNight: 13400, currency: "INR" },
    averageRating: 4.9,
    totalReviews: 144,
    status: "active",
    isFeatured: true,
    coverImage: "https://images.unsplash.com/photo-1455587734955-081b22074882?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=1200&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
    ],
    policies: { checkInTime: "15:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 5 days before check-in" },
    contact: { email: "stay@aurorasnowview.com", phone: "+91 1954 445 900" },
    roomThemes: [
      { code: "SV", name: "Snowview Room", multiplier: 0.82, adults: 2, children: 1, bedType: "Queen", roomSize: 320, totalRooms: 12, availableRooms: 8, amenities: ["Heater", "WiFi", "Snow View", "Tea Service", "Desk"] },
      { code: "FC", name: "Fireplace Cabin Suite", multiplier: 1.44, adults: 3, children: 2, bedType: "King", roomSize: 560, totalRooms: 6, availableRooms: 4, amenities: ["Fireplace", "Lounge", "Bathtub", "Coffee Press", "Balcony"] },
      { code: "AS", name: "Aurora Summit Residence", multiplier: 2.08, adults: 4, children: 2, bedType: "King", roomSize: 810, totalRooms: 3, availableRooms: 1, amenities: ["Private Spa", "Dining Space", "Butler Service", "Equipment Storage", "Panoramic View"] },
    ],
  },
  {
    hotelCode: "LUX020",
    name: "Moonlit Dunes Camp",
    brand: "LuxStay Adventure",
    slug: "moonlit-dunes-camp",
    description: "An upscale desert camp in Kutch with immersive craft experiences, quiet night skies, and modern comfort under canvas-inspired design.",
    starRating: 4,
    propertyType: "Resort",
    address: { addressLine1: "White Rann Circuit", city: "Kutch", state: "Gujarat", country: "India", pincode: "370510" },
    amenities: ["Desert Excursions", "WiFi", "Cultural Shows", "Restaurant", "Bonfire", "Parking", "Concierge"],
    pricing: { basePricePerNight: 7200, currency: "INR" },
    averageRating: 4.6,
    totalReviews: 119,
    status: "active",
    isFeatured: false,
    coverImage: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=80",
      "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1200&q=80",
      "https://images.unsplash.com/photo-1529551739587-e242c564f727?w=1200&q=80",
    ],
    policies: { checkInTime: "14:00", checkOutTime: "11:00", cancellationPolicy: "Free cancellation until 48 hours before check-in" },
    contact: { email: "hello@moonlitdunescamp.com", phone: "+91 2832 771 430" },
    roomThemes: [
      { code: "DC", name: "Desert Canvas Room", multiplier: 0.8, adults: 2, children: 1, bedType: "Queen", roomSize: 310, totalRooms: 14, availableRooms: 10, amenities: ["AC", "Tea Service", "Deck Chairs", "WiFi", "Wardrobe"] },
      { code: "MR", name: "Moonrise Suite", multiplier: 1.34, adults: 3, children: 1, bedType: "King", roomSize: 480, totalRooms: 6, availableRooms: 4, amenities: ["Outdoor Bath", "Lounge", "Cultural Setup", "Mini Bar", "Star Deck"] },
      { code: "WR", name: "White Rann Residence", multiplier: 1.92, adults: 4, children: 2, bedType: "King", roomSize: 720, totalRooms: 3, availableRooms: 2, amenities: ["Private Dining", "Sunrise Deck", "Butler Service", "Pantry", "Observation Lounge"] },
    ],
  },
];

const ROOM_IMAGE_SETS = [
  [
    "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80",
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=900&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=900&q=80",
    "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=900&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=900&q=80",
    "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1596436889106-be35e843f974?w=900&q=80",
    "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=900&q=80",
  ],
];

const offers = [
  {
    title: "Early Bird Special",
    description: "Book 30 days in advance and enjoy 30% off on all room categories.",
    code: "EARLY30",
    discountType: "PERCENT",
    discountValue: 30,
    minBookingAmount: 3000,
    maxDiscount: 5000,
    validFrom: new Date("2024-01-01"),
    validTill: new Date("2027-12-31"),
    applicableOn: "BOTH",
    isActive: true,
  },
  {
    title: "Weekend Break",
    description: "Save 20% on stays of 2 nights or more during weekends.",
    code: "WEEKEND20",
    discountType: "PERCENT",
    discountValue: 20,
    minBookingAmount: 2000,
    maxDiscount: 3000,
    validFrom: new Date("2024-01-01"),
    validTill: new Date("2027-12-31"),
    applicableOn: "BOTH",
    isActive: true,
  },
  {
    title: "Welcome Gift",
    description: "Enjoy INR 1,500 off your first LuxStay booking.",
    code: "FIRST1500",
    discountType: "FLAT",
    discountValue: 1500,
    minBookingAmount: 5000,
    validFrom: new Date("2024-01-01"),
    validTill: new Date("2027-12-31"),
    applicableOn: "BOTH",
    isActive: true,
  },
  {
    title: "Loyalty Bonus",
    description: "Returning guests get 15% off their next stay.",
    code: "LOYAL15",
    discountType: "PERCENT",
    discountValue: 15,
    minBookingAmount: 1000,
    maxDiscount: 4000,
    validFrom: new Date("2024-01-01"),
    validTill: new Date("2027-12-31"),
    applicableOn: "BOTH",
    isActive: true,
  },
  {
    title: "Monsoon Magic",
    description: "Flat INR 2,000 off selected seasonal stays.",
    code: "MONSOON2K",
    discountType: "FLAT",
    discountValue: 2000,
    minBookingAmount: 6000,
    validFrom: new Date("2024-01-01"),
    validTill: new Date("2027-12-31"),
    applicableOn: "BOTH",
    isActive: true,
  },
  {
    title: "Suite Dreams",
    description: "Get 25% off when you book any suite or premium room category.",
    code: "SUITE25",
    discountType: "PERCENT",
    discountValue: 25,
    minBookingAmount: 8000,
    maxDiscount: 6000,
    validFrom: new Date("2024-01-01"),
    validTill: new Date("2027-12-31"),
    applicableOn: "ROOM",
    isActive: true,
  },
];

function buildRoomDescription(hotel, theme) {
  return `${theme.name} at ${hotel.name} pairs ${hotel.propertyType.toLowerCase()} character with thoughtful premium comforts, tailored for ${theme.adults + (theme.children || 0)} guests.`;
}

function buildRoomsForHotel(hotel) {
  return (hotel.roomThemes || []).map((theme, index) => ({
    hotelId: hotel._id,
    roomTypeCode: theme.code,
    roomTypeName: theme.name,
    description: buildRoomDescription(hotel, theme),
    maxAdults: theme.adults,
    maxChildren: theme.children,
    bedType: theme.bedType,
    roomSize: theme.roomSize,
    amenities: theme.amenities,
    basePrice: Math.round(hotel.pricing.basePricePerNight * theme.multiplier),
    extraAdultPrice: Math.round(hotel.pricing.basePricePerNight * 0.12),
    extraChildPrice: Math.round(hotel.pricing.basePricePerNight * 0.06),
    totalRooms: theme.totalRooms,
    availableRooms: theme.availableRooms,
    images: ROOM_IMAGE_SETS[index % ROOM_IMAGE_SETS.length],
    status: theme.availableRooms > 0 ? "available" : "sold_out",
  }));
}

module.exports = {
  hotels,
  offers,
  buildRoomsForHotel,
};
